name: CD Pipeline to Coolify

on:
  push:
    branches:
      - staging
  workflow_dispatch: {}

env:
  IMAGE: ${{ vars.IMAGE }}:${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build, push Docker image, and deploy to Coolify
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate for Docker Hub
        env:
          D_USER: ${{ secrets.DOCKER_USER }}
          D_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$D_PASS" | docker login -u "$D_USER" --password-stdin

      - name: Build and tag image
        run: |
          docker build -t ${{ env.IMAGE }} .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.IMAGE }}

      - name: Deploy to Coolify
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
          --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"